version: 2.1

jobs:
  build-linux:
    working_directory: ~/repo
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install system dependencies (dpkg, fakeroot)
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot
      - run:
          name: Install project dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds (Linux)
          command: npm run make
      - store_artifacts:
          path: out/make

workflows:
  linux_build:
    jobs:
      - build-linux


